In [90]:
import pandas as pd
import numpy as np

In [91]:
dataset=pd.read_csv('Adult Census Income.csv')
dataset.head()

age workclass  fnlwgt     education  education.num marital.status  \
0   90         ?   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66         ?  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0                  ?  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2                  ?      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States  <=50K  
2          4356              40  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K

In [92]:
for i in dataset.columns:
    print(i)
    print(dataset[i].value_counts())
    print("------------------------------------------------------")

age
36    898
31    888
34    886
23    877
35    876
     ... 
83      6
85      3
88      3
86      1
87      1
Name: age, Length: 73, dtype: int64
------------------------------------------------------
workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: workclass, dtype: int64
------------------------------------------------------
fnlwgt
164190    13
123011    13
203488    13
113364    12
148995    12
          ..
201155     1
127384     1
270522     1
315804     1
145522     1
Name: fnlwgt, Length: 21648, dtype: int64
------------------------------------------------------
education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school

In [93]:
dataset['workclass']=dataset['workclass'].replace('?','Private')
dataset['occupation']=dataset['occupation'].replace('?','Prof-specialty')
dataset['native.country']=dataset['native.country'].replace('?','United-States')
dataset.head()

age workclass  fnlwgt     education  education.num marital.status  \
0   90   Private   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66   Private  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0     Prof-specialty  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2     Prof-specialty      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States  <=50K  
2          4356              40  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K

In [94]:
dataset['marital.status']=dataset['marital.status'].replace(['Married-AF-spouse','Married-civ-spouse'],'Married')
dataset['marital.status']=dataset['marital.status'].replace('Never-Married','Not Married')
dataset['marital.status']=dataset['marital.status'].replace(['Divorced','Separated','Married-spouse-absent','Widowed'],'Other')
dataset.head()

age workclass  fnlwgt     education  education.num marital.status  \
0   90   Private   77053       HS-grad              9          Other   
1   82   Private  132870       HS-grad              9          Other   
2   66   Private  186061  Some-college             10          Other   
3   54   Private  140359       7th-8th              4          Other   
4   41   Private  264663  Some-college             10          Other   

          occupation   relationship   race     sex  capital.gain  \
0     Prof-specialty  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2     Prof-specialty      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States  <=50K  
2          4356              40  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K

In [95]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [96]:
print(x)

[[90 'Private' 77053 ... 4356 40 'United-States']
 [82 'Private' 132870 ... 4356 18 'United-States']
 [66 'Private' 186061 ... 4356 40 'United-States']
 ...
 [40 'Private' 154374 ... 0 40 'United-States']
 [58 'Private' 151910 ... 0 40 'United-States']
 [22 'Private' 201490 ... 0 20 'United-States']]


In [97]:
print(y)

['<=50K' '<=50K' '<=50K' ... '>50K' '<=50K' '<=50K']


In [98]:
from sklearn.preprocessing import LabelEncoder
le1= LabelEncoder()
le3= LabelEncoder()
le5= LabelEncoder()
le6= LabelEncoder()
le7= LabelEncoder()
le8= LabelEncoder()
le9= LabelEncoder()
le13= LabelEncoder()
le= LabelEncoder()

x[:,1]= le1.fit_transform(x[:,1])
x[:,3]= le3.fit_transform(x[:,3])
x[:,5]= le5.fit_transform(x[:,5])
x[:,6]= le6.fit_transform(x[:,6])
x[:,7]= le7.fit_transform(x[:,7])
x[:,8]= le8.fit_transform(x[:,8])
x[:,9]= le9.fit_transform(x[:,9])
x[:,13]= le13.fit_transform(x[:,13])
y=le.fit_transform(y)

In [99]:
for i in x:
    print(i)

[90 3 77053 11 9 2 9 1 4 0 0 4356 40 38]
[82 3 132870 11 9 2 3 1 4 0 0 4356 18 38]
[66 3 186061 15 10 2 9 4 2 0 0 4356 40 38]
[54 3 140359 5 4 2 6 4 4 0 0 3900 40 38]
[41 3 264663 15 10 2 9 3 4 0 0 3900 40 38]
[34 3 216864 11 9 2 7 4 4 0 0 3770 45 38]
[38 3 150601 0 6 2 0 4 4 1 0 3770 40 38]
[74 6 88638 10 16 1 9 2 4 0 0 3683 20 38]
[68 0 422013 11 9 2 9 1 4 0 0 3683 40 38]
[41 3 70037 15 10 1 2 4 4 1 0 3004 60 38]
[45 3 172274 10 16 2 9 4 2 0 0 3004 35 38]
[38 5 164526 14 15 1 9 1 4 1 0 2824 45 38]
[52 3 129177 9 13 2 7 1 4 0 0 2824 20 38]
[32 3 136204 12 14 2 3 1 4 1 0 2824 55 38]
[51 3 172175 10 16 1 9 1 4 1 0 2824 40 38]
[46 3 45363 14 15 2 9 1 4 1 0 2824 40 38]
[45 3 172822 1 7 2 13 1 4 1 0 2824 76 38]
[57 3 317847 12 14 2 3 1 4 1 0 2824 50 38]
[22 3 119592 7 12 1 5 1 2 1 0 2824 40 38]
[34 3 203034 9 13 2 11 1 4 1 0 2824 50 38]
[37 3 188774 9 13 1 3 1 4 1 0 2824 40 38]
[29 3 77009 1 7 2 11 1 4 0 0 2754 42 38]
[61 3 29059 11 9 2 11 4 4 0 0 2754 25 38]
[51 3 153870 15 10 0 13 0 4 1 

In [100]:
print(y)

[0 0 0 ... 1 0 0]


In [101]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [103]:
from xgboost import XGBClassifier
model=XGBClassifier()
model.fit(X_train,Y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [104]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=model.predict(X_test)
cm=confusion_matrix(Y_test,y_pred)
print(cm)
accuracy_score(Y_test,y_pred)

[[4659  307]
 [ 551  996]]


0.8682634730538922

In [105]:
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=model,X=X_train,y=Y_train,cv=10)
print('Accuracy: {:.2f} Standard Deviation: {:.2f}'.format(accuracies.mean()*100,accuracies.std()*100))

Accuracy: 87.14 Standard Deviation: 0.67


In [106]:
import pickle 
pickle.dump(model,open("income_pred.pkl","wb"))

In [107]:
file=pickle.load(open("income_pred.pkl","rb"))

In [108]:
result=file.predict([[46,3,45363,14,15,2,9,1,4,1,0,2824,39]])
if result==[0]:
  print('Person makes Below 50K/year')
else:
  print('Person makes Above 50K/year')

Person makes Above 50K/year
